### ISSUE TITLE
Dynamic trees update breaks addon

### ISSUE THREAD

**Issue by mxnmnm** [the-realest-stu/Dynamic-Trees-TC#10]
I think you have a newer version of the thaumcraft compat loaded into your dynamic trees dev instance because my game is screaming at me that I need version 1.4.2 (unless it's already uploaded to curseforge and just hasn't gotten approved yet in which case you can just close this issue)

https://gist.github.com/mxnmnm/ad849bfce3912fb8a0dacd40f0a3795e

**Comment by ghost** [comment]
I'll have the new version out hopefully today.
