### ISSUE TITLE
Minecraft fails to load with Either Dynamic Trees or Dynamic Trees TC

### ISSUE THREAD

**Issue by ScienceDrummer** [the-realest-stu/Dynamic-Trees-TC#2]
Crash Report Dynamic Trees TC: https://pastebin.com/fgdR8N2g
Crash Report Dynamic Trees: https://pastebin.com/7RijU8x5

**Comment by ghost** [comment]
Am I missing something here?  I don't see anything in the logs that implicates Dynamic Trees or Dynamic Trees TC for the crash.  What lead you to believe this was the case?

**Comment by ScienceDrummer** [comment]
I guess I was a little too quick to jump the gun. I was looking in the crash report and I saw .dynamic so I figured it was the mod I just installed.

**Comment by ghost** [comment]
Because of the faulty nature of this bug report I'm going to have to ask you to do your due diligence and prove this is an issue related to dynamic trees and provide steps to replicate the issue.  Otherwise I'll have to dismiss it.  Thanks.

**Comment by ScienceDrummer** [comment]
Can you delete this? I found the reason for my crashes.
