### ISSUE TITLE
Silverwood seeds

### ISSUE THREAD

**Issue by lOmicronl** [the-realest-stu/Dynamic-Trees-TC#3]
I'm using this mod in combination with the latest Dynamic Trees, and Thaumcraft Beta 6.21. It works beautifully.

The only thing I have noticed: when I chop down a Silverwood tree, I'm getting 4-6 seeds every single time. Natively, Thaumcraft sets the sapling drop rate for Silverwood trees extremely low - like one sapling per two full trees on the grand average. Getting a Silverwood sapling should be considered a prized treasure, because planting a tree near your base has strong positive effects.

Now, I don't know anything about how Dynamic Trees does things, but is it possible to change the seed drop rate on an individual tree basis, so that Silverwood seeds can be made as rare as they were intended to be?

**Comment by ghost** [comment]
It certainly is possible and shouldn't be a problem to make this change.

**Comment by lOmicronl** [comment]
Great to hear! :)

**Comment by cadaverous-eris** [comment]
Fixed in the version released a few weeks ago.
