### ISSUE TITLE
Chopping down greatwood tree caused crash

### ISSUE THREAD

**Issue by SeriousCreeper** [the-realest-stu/Dynamic-Trees-TC#5]
Crash Report: https://pastebin.com/zRDu2FMA 

Using version dynamic trees 0.9.1d and dynamic trees - tc 1.4.1a 
Forge version: 14.23.5.2778

I was breaking the lower part of the tree, saw the beginning of the breaking overlay texture and then crashed after 2 or so seconds (before the tree was completely broken down).

**Comment by ghost** [comment]
Can you confirm this doesn't happen after you update Dynamic Trees and the Thaumcraft Add-on to the latest versions?

**Comment by ghost** [comment]
Bug fixed in base DT mod
