### ISSUE TITLE
Small Problem with texture packs and thick trees!

### ISSUE THREAD

**Issue by SirAron111** [the-realest-stu/Dynamic-Trees-TC#6]
Thick Trees don’t grab the textures not even in a stretched form or anything and will always turn to vanilla textures once the normal block size is overtaken. The roots will still use the textures from texture packs I made some pictures to show this.
![2018-12-26_15 21 03](https://user-images.githubusercontent.com/39855956/50449068-20c91600-0925-11e9-9e92-be0f82ab243b.png)
![2018-12-26_15 21 18](https://user-images.githubusercontent.com/39855956/50449069-20c91600-0925-11e9-817d-82b7a54ce604.png)

**Comment by ghost** [comment]
What this amounts to is that the log bark texture assets that Thaumcraft uses has a horizontal gradient across it's surface which is not good.  Presumably this was to give the log a superficial rounded appearance. This makes the repeating texture have a very ugly and distinct border on it's left/right sides.  To combat this problem Mangoose made a custom texture asset that matches the original as best as possible while removing the gradient from it so it tiles properly on thick trees.  This asset it part of the add-on.  If you want the texture to look proper with your resource pack you'll need to add an asset to said pack to override the custom texture we had to make.  Browsing the add-on's assets in the jar file should clarify things.

**Comment by SirAron111** [comment]
Looks like simply copping the image for the log texture and renaming the copy with thick at the end actually fixes it. Well the rounding texture is there thought. But not noticeably much, now I need to find a texture add-on maker maker to make this into a proper add-on XD who is better than me with my makeshift copy pasta idea. Or just ask the one who makes the thaumcraft textures to include it its just 2 images after all and I think many people will be using the dynamic trees in the future as they are just plain awesome
![2018-12-26_19 00 41](https://user-images.githubusercontent.com/39855956/50453555-b2df1780-0941-11e9-85bf-ea7384efbc2b.png)
![2018-12-26_19 01 39](https://user-images.githubusercontent.com/39855956/50453556-b377ae00-0941-11e9-8802-956292a7f0af.png)
