### ISSUE TITLE
Trees are not being replaced with dynamic variants

### ISSUE THREAD

**Issue by Tank-Missile** [the-realest-stu/Dynamic-Trees-TC#7]
I'd say It's a 50/50 chance that a thaumcraft greatwood or silverbell tree spawns as dynamic or normal.

**Comment by kierajreed** [comment]
Please post which mods you are using and their versions.

**Comment by Tank-Missile** [comment]
I'm creating my own modpack with this mod included, but decided for easier debugging to test the minimal mods needed to get this mod working. Unfortunatly, the same issue is still present.

Baubles 1.12-1.5.2
Dynamic Trees 1.12.2-0.9.1i
Dynamic Trees TC 1.12.2-1.4.1e
Thaumcraft 1.12.2-6.1.BETA26

**Comment by laserlemons** [comment]
I'm also seeing this issue on my server but I can't make any sense of it. Any new world I create with the same modpack works fine. The only thing I can think of is that I did turn on Thaumcraft's retro-generation briefly around the beginning of the server, but it has been turned off since then.

**Comment by Tank-Missile** [comment]
[I guess it doesn't matter since Thaumcraft is dead now...](https://www.patreon.com/posts/sad-farewell-23967282)

**Comment by laserlemons** [comment]
It's not dead until people stop playing it!

**Comment by laserlemons** [comment]
Now I can't get it to work in any world I make. This is weird.

**Comment by Graywaren** [comment]
This appears to be because the latest version isn't disabling Thaumcraft world cfg tree generation. Mentioned in this issue. Setting that to false seems to remove the vanilla trees
https://github.com/the-realest-stu/DynamicTrees-TC/issues/8

**Comment by TheSexyYeti** [comment]
Same issue here. I wanna keep Dynamic Trees in the mod pack I'm building for me an my friends. But if I'm gonna have the issue of it not replacing the tree it's made to replace. Then there's no point in even having it.
