### ISSUE TITLE
Normal Thaumcraft tree generation not being disabled

### ISSUE THREAD

**Issue by laserlemons** [the-realest-stu/Dynamic-Trees-TC#8]
This is probably the cause of that other issue. I had to manually turn off tree generation in the Thaumcraft World config in order to stop the normal trees from spawning alongside the dynamic trees.

**Comment by laserlemons** [comment]
Sorry for all the edits. I accidentally hit enter before I was done typing.

**Comment by Graywaren** [comment]
Can confirm. Had to disable this as well. Seems to  have fixed the issue.

**Comment by VinterNacht** [comment]
I disabled tree spawning in the Normal Thaumcraft World Config and it seems to have stopped them from spawning altogether, DT version and otherwise.

**Comment by LukaPix** [comment]
This is still an issue.
The trees generate as default TC Trees oder do not generate at all.

**Comment by ghost** [comment]
I think this has to do with the regenTrees option.  If it's enabled it will generate vanilla style TC trees in existing chunks bypassing our forced disabling of the option.

**Comment by laserlemons** [comment]
I'm still seeing the normal kind of thaumcraft trees generating alongside the dynamic kind in new worlds using the latest version.

**Comment by LukaPix** [comment]
I do see that too and no it is not because of regenTrees, i have that disabled

**Comment by Xiaminou** [comment]
same problem.
